name: repro

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  repro:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      id-token: write
    env:
      WORKING_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
    steps:
      - name: assume role
        id: assume-role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::677771948337:role/cache-miss-repro-role
          role-session-name: assume-role-session
          aws-region: us-west-2

      # - name: install dive
      #   id: install-dive
      #   run: |
      #     curl -fOL "https://github.com/wagoodman/dive/releases/download/v0.13.1/dive_0.13.1_linux_arm64.deb"
      #     sudo apt install ./dive_0.13.1_linux_arm64.deb

      - name: install buildx
        id: install-buildx
        uses: docker/setup-buildx-action@v3 
        with:
          version: v0.23.0

      - name: checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.WORKING_SHA }}

      - name: build
        id: build
        run: |
          TAG=test:test \
          docker buildx bake to
      
      - name: export
        id: export
        run: |
          aws s3 cp .cache s3://kaixo-buildx-cache/.cache

      # - name: layers
      #   id: layers
      #   run: |
      #     dive test:test --json dive.json
      #     aws s3 cp dive.json s3://kaixo-buildx-cache/dive.json