name: repro

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  repro:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      id-token: write
    env:
      WORKING_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
    steps:
      - name: assume role
        id: assume-role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::677771948337:role/cache-miss-repro-role
          role-session-name: assume-role-session
          aws-region: us-west-2

      - name: setup containerd
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: install buildx
        id: install-buildx
        uses: docker/setup-buildx-action@v3 
        with:
          version: v0.23.0
          use: false

      - name: install just
        id: install-just
        uses: extractions/setup-just@v3

      - name: checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.WORKING_SHA }}

      - name: builder up
        id: builder-up
        run: |
          just up

      - name: build
        id: build
        run: |
          just

